// default package
// Generated 3-Feb-2014 7:26:12 PM by Hibernate Tools 4.0.0

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class Course implements java.io.Serializable {

	private int courseId;
	private String courseName;
	private Set students = new HashSet(0);

	public Course() {
	}

	public Course(int courseId) {
		this.courseId = courseId;
	}

	public Course(int courseId, String courseName, Set students) {
		this.courseId = courseId;
		this.courseName = courseName;
		this.students = students;
	}

	public Course(int courseId, String courseName) {
		this.courseId = courseId;
		this.courseName = courseName;
	}

	public int getCourseId() {
		return this.courseId;
	}

	public void setCourseId(int courseId) {
		this.courseId = courseId;
	}

	public String getCourseName() {
		return this.courseName;
	}

	public void setCourseName(String courseName) {
		this.courseName = courseName;
	}

	public Set getStudents() {
		return this.students;
	}

	public void setStudents(Set students) {
		this.students = students;
	}

}
